export const OMNIROUTE_RESPONSE_HEADERS = {
  cache: "X-OmniRoute-Cache",
  cacheHit: "X-OmniRoute-Cache-Hit",
  cacheLatency: "X-OmniRoute-Cache-Latency",
  connectionId: "X-OmniRoute-Connection-Id",
  compression: "X-OmniRoute-Compression",
  accountingKind: "X-OmniRoute-Accounting-Kind",
  costSaved: "X-OmniRoute-Cost-Saved",
  costSource: "X-OmniRoute-Cost-Source",
  costCurrency: "X-OmniRoute-Cost-Currency",
  decision: "X-OmniRoute-Decision",
  fallbackAttempts: "X-OmniRoute-Fallback-Attempts",
  latencyMs: "X-OmniRoute-Latency-Ms",
  model: "X-OmniRoute-Model",
  progress: "X-OmniRoute-Progress",
  provider: "X-OmniRoute-Provider",
  requestId: "X-OmniRoute-Request-Id",
  responseCost: "X-OmniRoute-Response-Cost",
  servedModel: "X-OmniRoute-Served-Model",
  servedProvider: "X-OmniRoute-Served-Provider",
  tokensIn: "X-OmniRoute-Tokens-In",
  tokensOut: "X-OmniRoute-Tokens-Out",
  usageKind: "X-OmniRoute-Usage-Kind",
  tokensPerSecond: "X-OmniRoute-Tokens-Per-Second",
  version: "X-OmniRoute-Version",
} as const;
